---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
  namespace: microservice-b
  labels:
    app.kubernetes.io/instance: microservice-b
    app.kubernetes.io/part-of: microservice-b
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: microservice-b
      role: app
  template:
    metadata:
      labels:
        service: microservice-b
        role: app
    spec:
      serviceAccountName: microservice-b
      containers:
        - name: microservice-b
          image: harbor.34.84.199.182.nip.io/library/microservice-b:03e382cdedaecd6f607f3926642ad0da77e68331
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b
  namespace: microservice-b
  labels:
    app.kubernetes.io/instance: microservice-b
    app.kubernetes.io/part-of: microservice-b
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    service: microservice-b
    role: app

